title: "Mobashshir Mahmood"
description: "Personal website and portfolio"
url: "https://mmahmood13.github.io"
baseurl: ""  # this stays empty for user.github.io sites

author:
  name: "Mobashshir Mahmood"
  avatar: "/assets/images/profile.jpg"  # Make sure this matches your uploaded file
  bio: "Aspiring researcher, writer, and photographer."
  email: "your@email.com"  # Replace with your actual email

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
