title: "Mobashshir Mahmood"
description: "Personal website and portfolio"
url: "https://mmahmood13.github.io"
baseurl: ""  # keep this blank for user.github.io sites

author:
  name: "Mobashshir Mahmood"
  email: "mmahmood.ure@gmail.com"  # <-- change to your email

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
